export const types = {
  ALBUM_GET_ALL_REQUEST: "ALBUM_GET_ALL_REQUEST",
  ALBUM_GET_ALL_SUCCESS: "ALBUM_GET_ALL_SUCCESS",
  ALBUM_GET_ALL_FAILED: "ALBUM_GET_ALL_FAILED",
  ALBUM_GET_BY_ID_REQUEST: "ALBUM_GET_BY_ID_REQUEST",
  ALBUM_GET_BY_ID_SUCCES: "ALBUM_GET_BY_ID_SUCCES",
  ALBUM_GET_BY_ID_FAILED: "ALBUM_GET_BY_ID_FAILED"
};

export const getAllAlbum = () => ({ type: types.ALBUM_GET_ALL_REQUEST });

export const getAlbumById = id => ({ type: types.ALBUM_GET_BY_ID_REQUEST, id });
