export const types = {
  PHOTO_GET_ALL_FAILED: "PHOTO_GET_ALL_FAILED",
  PHOTO_GET_LESS_FAILED: "PHOTO_GET_LESS_FAILED",
  PHOTO_GET_BY_ID_FAILED: "PHOTO_GET_BY_ID_FAILED",
  PHOTO_GET_ALL_REQUEST: "PHOTO_GET_ALL_REQUEST",
  PHOTO_GET_LESS_REQUEST: "PHOTO_GET_LESS_REQUEST",
  PHOTO_GET_BY_ID_REQUEST: "PHOTO_GET_BY_ID_REQUEST",
  PHOTO_GET_ALL_SUCCESS: "PHOTO_GET_ALL_SUCCESS",
  PHOTO_GET_LESS_SUCCESS: "PHOTO_GET_LESS_SUCCESS",
  PHOTO_GET_BY_ID_SUCCESS: "PHOTO_GET_BY_ID_SUCCESS"
};

export const getLessPhoto = count => ({
  type: types.PHOTO_GET_LESS_REQUEST,
  count
});

export const getAllPhoto = () => ({ type: types.PHOTO_GET_ALL_REQUEST });

export const getPhotoById = id => ({ type: types.PHOTO_GET_BY_ID_REQUEST, id });
