export default [
  {
    albumId: 1,
    id: 1,
    title: 'accusamus beatae ad facilis cum similique qui sunt',
    url: 'https://via.placeholder.com/600/92c952',
    thumbnailUrl: 'https://via.placeholder.com/150/92c952',
  },
  {
    albumId: 58,
    id: 2879,
    title: 'nihil nostrum quos fugit molestias sed',
    url: 'https://via.placeholder.com/600/1b6987',
    thumbnailUrl: 'https://via.placeholder.com/150/1b6987',
  },
  {
    albumId: 78,
    id: 3874,
    title: 'ipsam sunt rerum quasi optio quibusdam doloremque distinctio',
    url: 'https://via.placeholder.com/600/9f343e',
    thumbnailUrl: 'https://via.placeholder.com/150/9f343e',
  },
  {
    albumId: 78,
    id: 3875,
    title: 'fugit repellat illum velit qui inventore accusamus perspiciatis',
    url: 'https://via.placeholder.com/600/4984ab',
    thumbnailUrl: 'https://via.placeholder.com/150/4984ab',
  },
  {
    albumId: 78,
    id: 3876,
    title: 'est dolorem ad ut',
    url: 'https://via.placeholder.com/600/79b825',
    thumbnailUrl: 'https://via.placeholder.com/150/79b825',
  },
  {
    albumId: 78,
    id: 3877,
    title: 'nisi suscipit in',
    url: 'https://via.placeholder.com/600/dd3063',
    thumbnailUrl: 'https://via.placeholder.com/150/dd3063',
  },
  {
    albumId: 78,
    id: 3878,
    title: 'voluptatem consequuntur omnis ducimus libero assumenda incidunt',
    url: 'https://via.placeholder.com/600/c37f9b',
    thumbnailUrl: 'https://via.placeholder.com/150/c37f9b',
  },
  {
    albumId: 78,
    id: 3879,
    title: 'amet placeat voluptatem ut perferendis similique incidunt deserunt aut',
    url: 'https://via.placeholder.com/600/b79bf2',
    thumbnailUrl: 'https://via.placeholder.com/150/b79bf2',
  },
  {
    albumId: 78,
    id: 3880,
    title: 'fugiat et impedit modi aut praesentium ex quisquam',
    url: 'https://via.placeholder.com/600/c610dd',
    thumbnailUrl: 'https://via.placeholder.com/150/c610dd',
  },
  {
    albumId: 78,
    id: 3881,
    title: 'expedita eos numquam qui',
    url: 'https://via.placeholder.com/600/9b0907',
    thumbnailUrl: 'https://via.placeholder.com/150/9b0907',
  },
  {
    albumId: 78,
    id: 3882,
    title: 'eum at voluptatibus',
    url: 'https://via.placeholder.com/600/4e899d',
    thumbnailUrl: 'https://via.placeholder.com/150/4e899d',
  },
  {
    albumId: 78,
    id: 3883,
    title: 'voluptas fugit fugiat ipsum et vel',
    url: 'https://via.placeholder.com/600/1c25c3',
    thumbnailUrl: 'https://via.placeholder.com/150/1c25c3',
  },
  {
    albumId: 78,
    id: 3884,
    title: 'est excepturi et eos rerum quia consectetur',
    url: 'https://via.placeholder.com/600/9e34d9',
    thumbnailUrl: 'https://via.placeholder.com/150/9e34d9',
  },
  {
    albumId: 78,
    id: 3885,
    title: 'pariatur dolorem autem voluptatem eum et sed repellendus',
    url: 'https://via.placeholder.com/600/20a281',
    thumbnailUrl: 'https://via.placeholder.com/150/20a281',
  },
  {
    albumId: 78,
    id: 3890,
    title: 'sed est perspiciatis sed',
    url: 'https://via.placeholder.com/600/c4bd4',
    thumbnailUrl: 'https://via.placeholder.com/150/c4bd4',
  },
  {
    albumId: 78,
    id: 3891,
    title: 'perspiciatis aperiam eligendi ab sed laudantium',
    url: 'https://via.placeholder.com/600/8e931',
    thumbnailUrl: 'https://via.placeholder.com/150/8e931',
  },
  {
    albumId: 78,
    id: 3892,
    title: 'quibusdam ipsam sed dolores eaque provident neque quis',
    url: 'https://via.placeholder.com/600/8ebc1f',
    thumbnailUrl: 'https://via.placeholder.com/150/8ebc1f',
  },
  {
    albumId: 96,
    id: 4796,
    title: 'libero magnam dolorem magni eveniet',
    url: 'https://via.placeholder.com/600/31852e',
    thumbnailUrl: 'https://via.placeholder.com/150/31852e',
  },
  {
    albumId: 100,
    id: 4965,
    title: 'officia autem eaque alias',
    url: 'https://via.placeholder.com/600/d04ed2',
    thumbnailUrl: 'https://via.placeholder.com/150/d04ed2',
  }
];
